# email_utils.py
import smtplib
from email.message import EmailMessage
from typing import Optional, List

# Import SMTP configuration from config.py
from config import Config

# Use SMTP settings from Config
SMTP_HOST = getattr(Config, 'SMTP_HOST', 'smtp.gmail.com')
SMTP_PORT = getattr(Config, 'SMTP_PORT', 587)
SMTP_USER = getattr(Config, 'SMTP_USER', 'myworkflow53@gmail.com')
SMTP_PASSWORD = getattr(Config, 'SMTP_PASSWORD', 'igmr piff qwoy qpnh')
SMTP_USE_TLS = getattr(Config, 'SMTP_USE_TLS', True)
DASHBOARD_BASE_URL = getattr(Config, 'DASHBOARD_BASE_URL', 'https://your-ngrok-url.ngrok.io')


def send_email(
        to_email: str,
        subject: str,
        body: str,
        cc: Optional[List[str]] = None,
        bcc: Optional[List[str]] = None
) -> bool:
    """
    Send an email using configured SMTP.
    Returns True if successful, False otherwise.
    """
    try:
        msg = EmailMessage()
        msg["Subject"] = subject
        msg["From"] = SMTP_USER
        msg["To"] = to_email
        if cc:
            msg["Cc"] = ", ".join(cc)
        if bcc:
            msg["Bcc"] = ", ".join(bcc)
        msg.set_content(body)

        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            if SMTP_USE_TLS:
                server.starttls()
            server.login(SMTP_USER, SMTP_PASSWORD)
            server.send_message(msg)
        return True
    except Exception as e:
        print(f"Email sending failed: {e}")
        return False


def send_user_invite_email(full_name: str, email: str, role: str, password: str) -> bool:
    """
    Send dashboard invite email to a new user.
    Password is generated by admin and cannot be changed by user.
    """
    subject = f"Welcome to Shortcaike Beauty Stores Dashboard – {role.title()} Access"
    body = f"""Hello {full_name},

You have been added as a {role} to the Shortcaike Beauty Stores dashboard.

Login details:
URL: {DASHBOARD_BASE_URL}/dashboard/login
Username: {email}
Password: {password}

If you did not request this, please ignore this email.

Regards,
Shortcaike Beauty Stores Admin
"""
    return send_email(email, subject, body)


def send_order_status_email(to_email: str, order_id: str, status: str, customer_name: str = None) -> bool:
    """
    Send email notification for order status updates.
    (Optional – currently WhatsApp is primary channel.)
    """
    subject = f"Order {order_id} – {status.replace('_', ' ').title()}"
    body = f"""Hello {customer_name or 'Customer'},

Your order {order_id} status has been updated to: {status.replace('_', ' ').upper()}.

Log in to your dashboard to view details:
{DASHBOARD_BASE_URL}/dashboard/login

Thank you,
Shortcaike Beauty Stores
"""
    return send_email(to_email, subject, body)


def send_payment_receipt_reminder(to_email: str, order_id: str, amount: float) -> bool:
    """
    Send reminder to customer to upload payment receipt.
    """
    subject = f"Payment Reminder for Order {order_id}"
    body = f"""Hello,

Please send your payment receipt for order {order_id} (₦{amount:,.0f}) to complete your purchase.

Upload your receipt via WhatsApp or reply to this email with the receipt attached.

Regards,
Shortcaike Beauty Stores
"""
    return send_email(to_email, subject, body)